services:
  # ollama:
  #   image: ollama/ollama:latest
  #   container_name: ollama
  #   restart: unless-stopped
  #   ports:
  #     - "11434:11434"
  #   volumes:
  #     - ollama_data:/root/.ollama

  mcp-server:
    build:
      context: ./mcp-server
      dockerfile: Dockerfile
    container_name: mcp-server
    restart: unless-stopped
    ports: 
      - "8000:8000"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 10s

  robot-agent:
    build:
      context: ./robot-agent
      dockerfile: Dockerfile
    container_name: robot-agent
    restart: unless-stopped
    ports: 
      - "5000:5000"
    depends_on: 
      mcp-server:
        condition: service_healthy
    environment:
      - OLLAMA_MODEL=llama3.2:3b
      - API_PORT=5000
      - MCP_SERVER_URL=http://mcp-server:8000/mcp
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
    extra_hosts:
      - "host.docker.internal:host-gateway"

#   open-webui:
#     image: ghcr.io/open-webui/open-webui:main
#     container_name: open-webui
#     restart: unless-stopped
#     # depends_on:
#     #   - ollama
#     ports:
#       - "3000:8080"
#     environment:
#       - OLLAMA_BASE_URL=http://host.docker.internal:11434
#     volumes:
#       - open_webui_data:/app/backend/data

# volumes:
#   # ollama_data:
#   open_webui_data:
