services:
  robot-mcp-server:
    build:
      context: ./robot-mcp-server
      dockerfile: src/application/servers/mcp_server/Dockerfile
    container_name: robot-mcp-server
    restart: unless-stopped
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8000/health"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 10s
    devices:
      - "/dev/i2c-1:/dev/i2c-1"

  robot-agent-be:
    build:
      context: ./robot-agent-be
      dockerfile: Dockerfile
    container_name: robot-agent-be
    restart: unless-stopped
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 10s
    env_file:
      - ./robot-agent-be/.env
    environment:
      - MODEL=gpt-4o-mini
      - API_PORT=8080
      - ROBOT_SERVER_URL=http://robot-mcp-server:8000
    depends_on:
      robot-mcp-server:
        condition: service_healthy

  robot-streamer:
    build:
      context: ./robot-mcp-server
      dockerfile: src/application/servers/streamer/Dockerfile
    container_name: robot-streamer
    restart: unless-stopped
    environment:
      - WS_SERVER_URL=ws://robot-agent-be:8080
    devices:
      - "/dev/video0:/dev/video0"
    depends_on:
      robot-agent-be:
        condition: service_healthy

  robot-agent-fe:
    build:
      context: ./robot-agent-fe
      dockerfile: Dockerfile
      args:
        VITE_BACKEND_URL: ws://10.42.0.1/:8080
        VITE_BACKEND_REST_URL: http://10.42.0.1/:8080
    container_name: robot-agent-fe
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      robot-streamer:
        condition: service_started
