services:
  robot-mcp-server:
    build:
      context: .
      dockerfile: src/application/servers/mcp_server/Dockerfile
    container_name: robot-mcp-server
    restart: unless-stopped
    ports: 
      - "8000:8000"
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
  
  robot-streamer:
    build:
      context: .
      dockerfile: src/application/servers/streamer/Dockerfile
    container_name: robot-streamer
    restart: unless-stopped
    environment:
      - WS_SERVER_URL=RIO-DXRY4LFCF
    devices:
      - "/dev/video0:/dev/video0"
