build-up-mcp:
	docker compose up robot-mcp-server --build

build-up-streamer:
	docker compose up robot-streamer --build

build-up-streamer-dev:
	uv run python -m src.application.servers.streamer.streamer